---
title: "Cognitive Development and Mental Models"
author: "Greg Wilson"
output:
  ioslides_presentation:
    highlight: pygments
    widescreen: yes
---

## Mental models

It ain't what you don't know that gets you into trouble. It's what you know for sure that just ain't so.   
~ Mark Twain

Our goal is not to teach the syntax of a particular programming language, but to teach people how to think about programming (and about using computers in research more generally), and give learners a strong
mental model.

**What exactly do we mean by a mental model?**   One example is the ball-and-spring model of molecules that most of us encountered in high school chemistry. Atoms aren't actually balls, and their bonds aren't actually springs, but the model does a good job of helping people reason about chemical compounds and their reactions.

## Dreyfus model of skill acquisition

How learners progress from novice to expert

- A novice is someone who doesn't know what they don't know, i.e., they don't yet know what the key ideas in the domain are or how they relate. More precisely, a novice has not yet built a mental model of the domain. They therefore reason by analogy and guesswork, borrowing bits and pieces of their mental models of other domains which seem superficially similar. One sign that someone is a novice is that their questions "aren't even wrong".  
- A competent practitioner is someone who has a mental model that's good enough for everyday purposes. This model does not have to be completely accurate in order to be useful: for example, the average driver's mental model of how a car works probably doesn't include most of the complexities that a mechanical engineer would be concerned with. Competent practitioners can do normal tasks with normal effort under normal circumstances.  
- An expert is someone who can easily handle situations that are out of the ordinary, diagnose the causes of problems, and so on. 

## Constructing mental models

One key insight from research on cognitive development is that novices, competent practitioners, and experts each need to be taught differently.

Our goal with novices is to help them construct a working mental model so that they have something to attach facts to.

## Clearing up misconceptions

Clearing up misconceptions is as important as presenting correct information.

Types of misconceptions:

- Simple factual errors, such as believing that Vancouver is the capital of British Columbia. These are simple to correct, but getting the facts right is not enough on its own.  
- Broken models, such as believing that motion and acceleration must be in the same direction. We can address these by having them reason through examples to see contradictions.  
- Fundamental beliefs, such as "the world is only a few thousand years old" or "human beings cannot be affecting the planet's climate". These usually cannot be addressed in class, since they are deeply connected to the learner's social identity and cannot be reasoned away.

e.g. Software Carpenty's command line lesson teaches just 15 commands in 3 hours - constructing a mental model

## Challenge

Solving problems to correct broken mental models

From Epstein's Thinking Physics:  

Imagine that you have placed a cake of ice in a bathtub and then filled the tub to the rim with water. When the ice melts, does the water level go up (so that the tub overflows), go down, or stay the same?

## Different kinds of lessons

The cognitive differences between novices and competent practitioners also underpin the differences between two kinds of teaching materials. 

- A tutorial's purpose is to help newcomers to a field build a mental model  
- A manual's role, on the other hand, is to help competent practitioners fill in the gaps in their knowledge. 

Tutorials frustrate competent practitioners because they move too slowly and say things that are obvious (though of course they are anything but to newcomers). Equally, manuals frustrate novices because they use jargon and don't explain things. 