name: Suggest an improvement in a specific location
description: Tell us about how a particular section of the lesson could be improved
body:
  - type: textarea
    id: details
    attributes:
      label: How could the content be improved?
      description: Please provide details of the improvement you are suggesting, to make it easier for the Maintainers and other community members to address the issue.
    validations:
      required: true
  - type: input
    id: location-details
    attributes:
      label: Which part of the content does your suggestion apply to?
      description: Please provide a URL, the title of the relevant section or page, a filename, etc.
  - type: markdown
    attributes:
      value: >
        Thank you for taking time to suggest an improvement to this repository.
        Before you submit the issue, please make sure you have read [The Carpentries Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)
        
        Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. 
        If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, 
        please contact The Carpentries Team at team@carpentries.org.
